### ISSUE TITLE
Victim: Host Info OS, GW, Users, Configs, etc.   C

### ISSUE THREAD

**Issue by Acidcreature** [Acidcreature/TEAMPROJRAT#2]
WIP Hackett

**Comment by Hackman9912** [comment]
`#include <stdio.h>
#include <stdlib.h>

main()
{
    // open and close a file to make sure it exists
    FILE * sysInfoFile = fopen("C:\\Users\\student\\Desktop\\C project\\sysInfoFile.txt", "w"); 
    fclose(sysInfoFile);
    // run the command sending the output to the file
    system("systeminfo > sysInfoFile.txt");
    // close C
    return 0;
}
`

**Comment by Hackman9912** [comment]
`#include <windows.h>
#include <stdio.h>
#pragma comment(lib, "user32.lib")

void main()
{
   SYSTEM_INFO siSysInfo;

   // Copy the hardware information to the SYSTEM_INFO structure. 

   GetSystemInfo(&siSysInfo); 

   // Display the contents of the SYSTEM_INFO structure. 

   printf("Hardware information: \n");  
   printf("  OEM ID: %u\n", siSysInfo.dwOemId);
   printf("  Number of processors: %u\n", 
      siSysInfo.dwNumberOfProcessors); 
   printf("  Page size: %u\n", siSysInfo.dwPageSize); 
   printf("  Processor type: %u\n", siSysInfo.dwProcessorType); 
   printf("  Minimum application address: %lx\n", 
      siSysInfo.lpMinimumApplicationAddress); 
   printf("  Maximum application address: %lx\n", 
      siSysInfo.lpMaximumApplicationAddress); 
   printf("  Active processor mask: %u\n", 
      siSysInfo.dwActiveProcessorMask); 
}`
